exp_name: baseline_resnet18
seed: 42
data_root: ../Oxford-IIIT
output_root: ./outputs
num_classes: 37
model_name: resnet18
pretrained: true
attention: none
img_size: 224
batch_size: 32
num_workers: 2
epochs: 20
optimizer: sgd
momentum: 0.9
backbone_lr: 0.0001
head_lr: 0.001
weight_decay: 0.0001
scheduler: cosine
